"""Cria tabelas iniciais

Revision ID: 0001
Revises: 
Create Date: 2026-01-07 20:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto-generated by Alembic - please adjust! ###
    op.create_table('contas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contas_email'), 'contas', ['email'], unique=True)
    op.create_index(op.f('ix_contas_id'), 'contas', ['id'], unique=False)
    
    op.create_table('agentes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('conta_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['conta_id'], ['contas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agentes_id'), 'agentes', ['id'], unique=False)
    op.create_index(op.f('ix_agentes_nome'), 'agentes', ['nome'], unique=False)

    op.create_table('itens_conhecimento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('dados_json', sa.JSON(), nullable=False),
    sa.Column('agente_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agente_id'], ['agentes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itens_conhecimento_categoria'), 'itens_conhecimento', ['categoria'], unique=False)
    op.create_index(op.f('ix_itens_conhecimento_id'), 'itens_conhecimento', ['id'], unique=False)
    op.create_index(op.f('ix_itens_conhecimento_nome'), 'itens_conhecimento', ['nome'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto-generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_itens_conhecimento_nome'), table_name='itens_conhecimento')
    op.drop_index(op.f('ix_itens_conhecimento_id'), table_name='itens_conhecimento')
    op.drop_index(op.f('ix_itens_conhecimento_categoria'), table_name='itens_conhecimento')
    op.drop_table('itens_conhecimento')
    op.drop_index(op.f('ix_agentes_nome'), table_name='agentes')
    op.drop_index(op.f('ix_agentes_id'), table_name='agentes')
    op.drop_table('agentes')
    op.drop_index(op.f('ix_contas_id'), table_name='contas')
    op.drop_index(op.f('ix_contas_email'), table_name='contas')
    op.drop_table('contas')
    # ### end Alembic commands ###
